export const SAMPLE_MOVIES = [
  { id: 101, tmdb_id: 101, title: 'Oppenheimer', overview: 'The story of J. Robert Oppenheimer and the creation of the atomic bomb.', poster_url: '/8Gxv8gSFCU0XGDykEGvUP2R1n2ua.jpg', backdrop_url: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg', imdb_rating: 8.1, content_type: 'movie', release_date: '2023-07-21', director: 'Christopher Nolan', cast_members: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'], genres: ['drama', 'thriller'], platforms: [{ id: 119, name: 'Prime Video', logo: '' }] },
  { id: 102, tmdb_id: 102, title: 'The Shawshank Redemption', overview: 'A banker sentenced to life in prison forms a bond with a fellow inmate.', poster_url: '/9cjIGRiQagNMaGpP6VlVLlaIKnb.jpg', backdrop_url: '/kXfqcdQKsToO0OUXHcrNCHDBzO.jpg', imdb_rating: 9.3, content_type: 'movie', release_date: '1994-09-23', director: 'Frank Darabont', cast_members: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler'], genres: ['drama', 'crime'], platforms: [{ id: 8, name: 'Netflix', logo: '' }, { id: 119, name: 'Prime Video', logo: '' }] },
  { id: 103, tmdb_id: 103, title: 'The Godfather', overview: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.', poster_url: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', backdrop_url: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg', imdb_rating: 9.2, content_type: 'movie', release_date: '1972-03-14', director: 'Francis Ford Coppola', cast_members: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Diane Keaton'], genres: ['drama', 'crime'], platforms: [{ id: 119, name: 'Prime Video', logo: '' }] },
  { id: 201, tmdb_id: 201, title: 'Avengers: Infinity War', overview: 'The Avengers must stop Thanos from collecting all six Infinity Stones.', poster_url: '/7WsyChQLEftFiDhRkfUP2AikFss.jpg', backdrop_url: '/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg', imdb_rating: 8.4, content_type: 'movie', release_date: '2018-04-25', director: 'Anthony Russo', cast_members: ['Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo', 'Chris Evans'], genres: ['action', 'sci-fi'], platforms: [{ id: 122, name: 'Hotstar', logo: '' }] },
  { id: 202, tmdb_id: 202, title: 'Spider-Man: Across the Spider-Verse', overview: 'Miles Morales catapults across the multiverse, meeting a team of Spider-People.', poster_url: '/8Vt6mWEReuy60MxNp7HKFyZFhZu.jpg', backdrop_url: '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg', imdb_rating: 8.6, content_type: 'movie', release_date: '2023-05-31', director: 'Joaquim Dos Santos', cast_members: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac'], genres: ['action', 'animation'], platforms: [{ id: 8, name: 'Netflix', logo: '' }] },
  { id: 203, tmdb_id: 203, title: 'The Dark Knight', overview: 'Batman must accept one of the greatest tests to fight injustice.', poster_url: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', backdrop_url: '/nMKdUUep0hQy2iIHJ7o5n0N9uUe7.jpg', imdb_rating: 9.0, content_type: 'movie', release_date: '2008-07-16', director: 'Christopher Nolan', cast_members: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine'], genres: ['action', 'crime', 'drama'], platforms: [{ id: 119, name: 'Prime Video', logo: '' }] },
  { id: 301, tmdb_id: 301, title: 'Get Out', overview: 'A young African-American visits his white girlfriend\'s parents for the weekend.', poster_url: '/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg', backdrop_url: '/wSMdJmkr7pBOsmATh2PqxW9gR0u.jpg', imdb_rating: 7.6, content_type: 'movie', release_date: '2017-02-24', director: 'Jordan Peele', cast_members: ['Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford'], genres: ['horror', 'thriller'], platforms: [{ id: 8, name: 'Netflix', logo: '' }] },
  { id: 302, tmdb_id: 302, title: 'A Quiet Place', overview: 'A family must live in silence to avoid mysterious creatures that hunt by sound.', poster_url: '/nAU74GmpUk7t5iklEp3bufwDq4n.jpg', backdrop_url: '/roYyPiQDQKmIKUEhO2fprvUx9k5.jpg', imdb_rating: 7.5, content_type: 'movie', release_date: '2018-04-03', director: 'John Krasinski', cast_members: ['Emily Blunt', 'John Krasinski', 'Millicent Simmonds'], genres: ['horror', 'thriller'], platforms: [{ id: 119, name: 'Prime Video', logo: '' }] },
  { id: 401, tmdb_id: 401, title: 'Inception', overview: 'A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.', poster_url: '/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg', backdrop_url: '/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg', imdb_rating: 8.4, content_type: 'movie', release_date: '2010-07-16', director: 'Christopher Nolan', cast_members: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'], genres: ['thriller', 'sci-fi', 'action'], platforms: [{ id: 8, name: 'Netflix', logo: '' }, { id: 119, name: 'Prime Video', logo: '' }] },
  { id: 402, tmdb_id: 402, title: 'Gone Girl', overview: 'A man finds himself the main suspect in the disappearance of his wife.', poster_url: '/lv5xShBIDPe6syEsMFkHf0oUJOJ.jpg', backdrop_url: '/gKMrJKd7MBNrvRxFSnMjFmitZwj.jpg', imdb_rating: 8.1, content_type: 'movie', release_date: '2014-10-01', director: 'David Fincher', cast_members: ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris'], genres: ['thriller', 'drama'], platforms: [{ id: 119, name: 'Prime Video', logo: '' }] },
  { id: 501, tmdb_id: 501, title: 'La La Land', overview: 'A jazz musician and an aspiring actress fall in love in Los Angeles.', poster_url: '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg', backdrop_url: '/p6h1gJlAZaKaImU10xd7Lz9VQb3pM.jpg', imdb_rating: 7.9, content_type: 'movie', release_date: '2016-11-29', director: 'Damien Chazelle', cast_members: ['Ryan Gosling', 'Emma Stone', 'John Legend'], genres: ['romance', 'comedy', 'drama'], platforms: [{ id: 8, name: 'Netflix', logo: '' }] },
  { id: 502, tmdb_id: 502, title: 'The Notebook', overview: 'A young couple falls in love during the early years of WWII.', poster_url: '/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg', backdrop_url: '/qom1SZSENdmHFNZBXbtJAU0WTlC.jpg', imdb_rating: 7.8, content_type: 'movie', release_date: '2004-06-25', director: 'Nick Cassavetes', cast_members: ['Ryan Gosling', 'Rachel McAdams', 'James Garner'], genres: ['romance', 'drama'], platforms: [{ id: 8, name: 'Netflix', logo: '' }, { id: 119, name: 'Prime Video', logo: '' }] },
  { id: 601, tmdb_id: 601, title: 'Parasite', overview: 'Greed and class discrimination threaten a symbiotic relationship between the wealthy Park family and the destitute Kim clan.', poster_url: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', backdrop_url: '/TU9NIjwzjoKPwQHoHshkFcQUCG8.jpg', imdb_rating: 8.5, content_type: 'movie', release_date: '2019-05-30', director: 'Bong Joon-ho', cast_members: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik'], genres: ['drama', 'comedy', 'thriller'], platforms: [{ id: 119, name: 'Prime Video', logo: '' }] }
];

export function getFallbackMovieByAnyId(movieId) {
  const numericId = typeof movieId === 'string' ? parseInt(movieId, 10) : movieId;
  if (!numericId || Number.isNaN(numericId)) return null;
  return SAMPLE_MOVIES.find(m => m.id === numericId || m.tmdb_id === numericId) || null;
}
